name: Compilar mod
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Descomprimir proyecto
        run: unzip -o proyecto.zip -d proyecto
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: Compilar
        working-directory: proyecto
        run: gradle build
      - uses: actions/upload-artifact@v4
        with:
          name: desinformados-mod
          path: proyecto/build/libs/*.jar
